package: developer
version: '3.1.0-alpha1'
author: Gregor Harlan
supportpage: http://www.redaxo.org/de/forum

page:
    title: translate:name
    perm: admin
    subpages:
        settings: { title: translate:settings }
