package: developer
version: '3.7.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/developer

page:
    title: translate:name
    perm: admin
    subpages:
        settings: { title: translate:settings }

console_commands:
    developer:sync: rex_developer_command

requires:
    php:
        extensions: [iconv]
