package: developer
version: '3.4.0'
author: Gregor Harlan
supportpage: http://www.redaxo.org/de/forum

page:
    title: translate:name
    perm: admin
    subpages:
        settings: { title: translate:settings }
